# 线上配置文件
server:
  port: 8101
  address: 0.0.0.0
spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://110.40.137.152:3306/wzx151212
    username: wzx151212
    password: Zr13970309103

  # rabbitmq 信息
  rabbitmq:
    host: 110.40.137.152
    password: Zr13970309103
    username: guest
    port: 5672

mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''
